version: '3'

services:
  minecraft:
    build:
      context: .
      args:
        VERSION: 1.18.1
    image: tarfeef101/mc_java_vanilla:alpine-1.18.1
    container_name: mc_javas
    restart: on-failure
    ports:
      - "8009:25565"
    volumes:
      - "./worlds:/opt/worlds"
      - "./config:/opt/config"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
