version: '3'

services:
  minecraft:
    build: .
    image: mc_java_vanilla:alpine-1.8.9
    container_name: mc_java
    restart: on-failure
    ports:
      - "8008:25565"
    volumes:
      - "./worlds:/opt/worlds"
      - "./config:/opt/config"
